name: Frontend CI/CD - MindCare

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # TEST & BUILD 
  test_frontend:
    name: Test & Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: |
          if [ -f .eslintrc.js ] || [ -f .eslintrc.json ]; then
            npm run lint
          else
            echo "No ESLint config found — skipping lint."
          fi

      - name: Run tests (skipped)
        run: echo "No frontend tests to run."

      - name: Build
        run: CI=false npm run build

  # DÉPLOIEMENT 
  deploy_frontend:
    name: Deploy to GCP
    needs: test_frontend 
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' 

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}        
          username: ${{ secrets.SSH_USER }}     
          key: ${{ secrets.SSH_PRIVATE_KEY }}   
          script: |
            cd ~/mindcare/web
            git remote set-url origin https://${{ secrets.GH_TOKEN }}@github.com/moslehSN/web.git
            git pull origin main
            echo "REACT_APP_API_URL=http://34.155.100.78:8000/api" > .env
            cd ..
            
            sudo docker compose up -d --build front